/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
/**
 *
 * @author Oleg
 */
public class NewApp extends javax.swing.JFrame {
    
    ArrayList<Class2> productList;
    private int currentInd;
    /**
     * Creates new form NewApp
     */
    public NewApp() {
        initComponents();
        productList = new ArrayList <Class2>();
        currentInd = productList.size()-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerCrn = new javax.swing.JSpinner();
        jTextFieldCount = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jFormattedTextFieldRelease = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonNew = new javax.swing.JButton();
        jButtonAge = new javax.swing.JButton();
        jButtonTV = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jFormattedTextFieldShip = new javax.swing.JTextField();
        jButtonDays = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("11 25");

        jLabel2.setText("Наименование товара");

        jLabel3.setText("Цена товара");

        jLabel4.setText("Год выпуска товара");

        jLabel8.setText("Дата поступления товара");

        jSpinnerCrn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCrnStateChanged(evt);
            }
        });

        jFormattedTextFieldRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldReleaseActionPerformed(evt);
            }
        });

        jButtonNew.setText("Новый товар");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonAge.setText("Возраст товара");
        jButtonAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgeActionPerformed(evt);
            }
        });

        jButtonTV.setText("Наценка за TV");

        jButtonDel.setText("Удалить товар");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonDays.setText("Количество дней с момента выпуска");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNew)
                                        .addGap(27, 27, 27)
                                        .addComponent(jButtonAge)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(jButtonTV))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldPrice)
                                            .addComponent(jFormattedTextFieldRelease, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))
                                .addGap(23, 23, 23)
                                .addComponent(jButtonDel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jFormattedTextFieldShip, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonDays, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonAge)
                    .addComponent(jButtonTV)
                    .addComponent(jButtonDel))
                .addGap(106, 106, 106)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDays)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
        setProduct();
        productList.add(new Class2());
        currentInd = productList.size()-1;
        getProduct();
        jTextFieldCount.setText(""+(currentInd+1));
        jSpinnerCrn.setValue(currentInd);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        productList.remove(currentInd);
        currentInd = productList.size()-1;
        if (currentInd == productList.size()){
            currentInd--;
            jSpinnerCrn.setValue(currentInd);
        } else {
            getProduct();
        }
        jTextFieldCount.setText("" + productList.size());
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jSpinnerCrnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCrnStateChanged
        // TODO add your handling code here:
        setProduct();
        currentInd = (int)jSpinnerCrn.getValue();
        if (currentInd >= productList.size()){
            currentInd = productList.size()-1;
            jSpinnerCrn.setValue(currentInd);
        } else if (currentInd <0){
            currentInd = 0;
            jSpinnerCrn.setValue(currentInd);
        }
        getProduct();
    }//GEN-LAST:event_jSpinnerCrnStateChanged

    private void jButtonAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgeActionPerformed
        // TODO add your handling code here:
        
       // productList.get(HowOld(year));
        setProduct();
        howOld();        
        getProduct();
    }//GEN-LAST:event_jButtonAgeActionPerformed

    private void jFormattedTextFieldReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldReleaseActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldRelease.setText(""+productList.get(currentInd).release);
      
    }//GEN-LAST:event_jFormattedTextFieldReleaseActionPerformed
    
    protected void setProduct(){
        if ((currentInd >= 0 )&& (jTextFieldName.getText() !=null)) {
            productList.get(currentInd).name = jTextFieldName.getText();
            productList.get(currentInd).ship = jFormattedTextFieldShip.getText();
            
            try {
                productList.get(currentInd).price = new Integer (jTextFieldPrice.getText());              
            }   catch (Exception e) {
                productList.get(currentInd).price = 0;
                jTextFieldPrice.setText(null);
            }
            try {
                productList.get(currentInd).release = new Integer (jFormattedTextFieldRelease.getText());
            }   catch (Exception e) {
                productList.get(currentInd).release = 0;
                jFormattedTextFieldRelease.setText(null);
            }         
        }
    }
    
    protected void getProduct(){
        if (currentInd >= 0) {
            jTextFieldName.setText(productList.get(currentInd).name); 
            jFormattedTextFieldShip.setText(productList.get(currentInd).ship);
            jFormattedTextFieldRelease.setText(""+productList.get(currentInd).release);
            jTextFieldPrice.setText(""+productList.get(currentInd).price);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAge;
    private javax.swing.JButton jButtonDays;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonTV;
    private javax.swing.JTextField jFormattedTextFieldRelease;
    private javax.swing.JTextField jFormattedTextFieldShip;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerCrn;
    private javax.swing.JTextField jTextFieldCount;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
